#!/usr/bin/env bash
# Installs Nginx with the following configurations:
# Listens on port 80.
# Returns a page containing "Hello World!" when queried
# at the root with a curl GET request.

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

# use sudo for auth
sudo service nginx restart
